import { Inter } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import Header from "./components/header";
import Footer from "./components/footer"
import '../../public/sass/helper/base.scss'
import '../../public/sass/helper/reset.scss'
import '../../public/sass/helper/helper.scss'

const inter = Inter({ subsets: ["latin"] });
// const poppins = Roboto({
//   subsets: ['latin'],
//   weights: [400, 700], // Specify the weights you need
// });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <head>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css" />
    </head>
      <body id="pb_scroll" className={inter.className}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
